name: "Install ImpressCMS"
description: "GitHub action to install ImpressCMS"

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: cpu
  color: "yellow"

inputs:
  url:
    description: "Site URL"
    default: http://localhost
    required: false
  database_type:
    description: "Database type"
    default: pdo.mysql
    required: false
  database_host:
    description: "Database host"
    default: 127.0.0.1
    required: false
  database_host_in_container:
    description: "Database host visible from inside installer container. Overrides automatic localhost mapping when set"
    default: ""
    required: false
  database_user:
    description: "Database user"
    required: true
  database_password:
    description: "Database password"
    default: ""
    required: false
  database_name:
    description: "Database name"
    default: icms
    required: false
  database_charset:
    description: "Charset used for database"
    default: utf8
    required: false
  database_collation:
    description: "Collation used for database"
    default: utf8_general_ci
    required: false
  database_prefix:
    description: "Prefix for each ImpressCMS database table"
    default: icms_${{ github.run_id }}_${{ github.run_attempt }}
    required: false
  database_port:
    description: "Port that is used for database connection"
    default: "3306"
    required: false
  admin_name:
    description: "Administrator name"
    default: icms
    required: false
  admin_login:
    description: "Administrator login string"
    default: icms
    required: false
  admin_pass:
    description: "Administrator password"
    default: icms
    required: false
  admin_email:
    description: "Administrator email"
    default: noreply@impresscms.dev
    required: false
  language:
    description: "Installation language"
    default: english
    required: false
  app_key:
    description: "Application key. If not specified and your ImpressCMS version supports it, it will be generated automatically"
    default: ""
    required: false
  path:
    description: "Where ImpressCMS is located?"
    default: "."
    required: false

outputs:
  app_key:
    description: Generated application key
  detected_impresscms_version:
    description: Detected ImpressCMS version in semver format
  uses_composer:
    description: Returns if current ImpressCMS version uses Composer for package management
  uses_phoenix:
    description: Returns if current ImpressCMS version uses Phoenix for migrations

runs:
  using: "node24"
  main: "dist/index.js"
